import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pressStart2P = localFont({
	src: "./fonts/pressStart2p.woff2",
	variable: "--font-dos",
	weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pressStart2P.variable} font-dos bg-dos-blue text-dos-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
